# Generated by Django 3.1 on 2023-03-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
